all: rhj

rhj:   general_functions.c lists.c rhj.c kapoies_oraies_sinartiseis.c ugly_functions_untested.c
	gcc -g3 -o rhj general_functions.c lists.c rhj.c kapoies_oraies_sinartiseis.c ugly_functions_untested.c -lm


